### ISSUE TITLE
TFP 1.46.0 data.ibm_atracker_* :Service URL for region not found for some of regions: ca-tor, jp-tok, jp-osa, br-sao

### ISSUE THREAD

**Issue by syyang-in-cloud** [IBM-Cloud/terraform-provider-ibm#4089]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* ibm_XXXXX

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
provider "ibm" {
  region = var.region
}

data "ibm_atracker_routes" "available" {}
data "ibm_atracker_targets" "available" {}
```

### Debug Output

```
2022-10-06T14:11:35.886Z [DEBUG] provider: starting plugin: path=.terraform/providers/registry.terraform.io/ibm-cloud/ibm/1.46.0/linux_amd64/terraform-provider-ibm_v1.46.0 args=[.terraform/providers/registry.terraform.io/ibm-cloud/ibm/1.46.0/linux_amd64/terraform-provider-ibm_v1.46.0]
2022-10-06T14:11:35.886Z [DEBUG] provider: plugin started: path=.terraform/providers/registry.terraform.io/ibm-cloud/ibm/1.46.0/linux_amd64/terraform-provider-ibm_v1.46.0 pid=3157
2022-10-06T14:11:35.886Z [DEBUG] provider: waiting for RPC address: path=.terraform/providers/registry.terraform.io/ibm-cloud/ibm/1.46.0/linux_amd64/terraform-provider-ibm_v1.46.0
2022-10-06T14:11:35.912Z [DEBUG] provider.terraform-provider-ibm_v1.46.0: 2022/10/06 14:11:35 IBM Cloud Provider version 1.46.0  
2022-10-06T14:11:35.912Z [INFO]  provider.terraform-provider-ibm_v1.46.0: configuring server automatic mTLS: timestamp=2022-10-06T14:11:35.912Z
2022-10-06T14:11:35.977Z [DEBUG] provider: using plugin: version=5
2022-10-06T14:11:35.977Z [DEBUG] provider.terraform-provider-ibm_v1.46.0: plugin address: address=/tmp/plugin056204679 network=unix timestamp=2022-10-06T14:11:35.977Z
2022-10-06T14:11:36.253Z [WARN]  ValidateProviderConfig from "provider[\"registry.terraform.io/ibm-cloud/ibm\"]" changed the config value, but that value is unused
2022-10-06T14:11:36.254Z [INFO]  provider.terraform-provider-ibm_v1.46.0: 2022/10/06 14:11:36 Configuring IBM Cloud Session with API key: timestamp=2022-10-06T14:11:36.254Z
2022-10-06T14:11:36.254Z [INFO]  provider.terraform-provider-ibm_v1.46.0: 2022/10/06 14:11:36 [INFO] Configured Region: jp-tok: timestamp=2022-10-06T14:11:36.254Z
2022-10-06T14:11:36.458Z [DEBUG] Resource instance state not found for node "data.ibm_atracker_targets.available", instance data.ibm_atracker_targets.available
2022-10-06T14:11:36.458Z [DEBUG] ReferenceTransformer: "data.ibm_atracker_targets.available" references: []
2022-10-06T14:11:36.458Z [DEBUG] Resource instance state not found for node "data.ibm_atracker_routes.available", instance data.ibm_atracker_routes.available
2022-10-06T14:11:36.458Z [DEBUG] ReferenceTransformer: "data.ibm_atracker_routes.available" references: []
data.ibm_atracker_targets.available: Reading...
data.ibm_atracker_routes.available: Reading...
2022-10-06T14:11:36.460Z [ERROR] vertex "data.ibm_atracker_routes.available" error: service URL for region 'jp-tok' not found
2022-10-06T14:11:36.460Z [ERROR] vertex "data.ibm_atracker_routes.available" error: service URL for region 'jp-tok' not found
2022-10-06T14:11:36.460Z [ERROR] vertex "data.ibm_atracker_routes.available (expand)" error: service URL for region 'jp-tok' not found
2022-10-06T14:11:36.460Z [ERROR] vertex "data.ibm_atracker_targets.available" error: service URL for region 'jp-tok' not found
2022-10-06T14:11:36.460Z [ERROR] vertex "data.ibm_atracker_targets.available" error: service URL for region 'jp-tok' not found
2022-10-06T14:11:36.460Z [ERROR] vertex "data.ibm_atracker_targets.available (expand)" error: service URL for region 'jp-tok' not found

Error: service URL for region 'jp-tok' not found

  with data.ibm_atracker_routes.available,
  on main.tf line 45, in data "ibm_atracker_routes" "available":
  45: data "ibm_atracker_routes" "available" {}


Error: service URL for region 'jp-tok' not found

  with data.ibm_atracker_targets.available,
  on main.tf line 46, in data "ibm_atracker_targets" "available":
  46: data "ibm_atracker_targets" "available" {}

```
### Actual Behavior

```
2022-10-06T14:21:31.316Z [ERROR] vertex "data.ibm_atracker_targets.available (expand)" error: service URL for region 'in-che' not found

Error: service URL for region 'in-che' not found

  with data.ibm_atracker_routes.available,
  on main.tf line 45, in data "ibm_atracker_routes" "available":
  45: data "ibm_atracker_routes" "available" {}


Error: service URL for region 'in-che' not found

  with data.ibm_atracker_targets.available,
  on main.tf line 46, in data "ibm_atracker_targets" "available":
  46: data "ibm_atracker_targets" "available" {}

```
### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by syyang-in-cloud** [comment]
I guess this issue comes from SDK typos: https://github.com/IBM/platform-services-go-sdk/blob/main/atrackerv2/atracker_v2.go
```go
func GetServiceURLForRegion(region string) (string, error) {
	var endpoints = map[string]string{
		"us-south": "https://us-south.atracker.cloud.ibm.com", // The server for IBM Cloud Activity Tracker Service in the us-south region.
		"private.us-south": "https://private.us-south.atracker.cloud.ibm.com", // The server for IBM Cloud Activity Tracker Service in the us-south region.
		"us-east": "https://us-east.atracker.cloud.ibm.com", // The server for IBM Cloud Activity Tracker Service in the us-east region.
		"private.us-east": "https://private.us-east.atracker.cloud.ibm.com", // The server for IBM Cloud Activity Tracker Service in the us-east region.
		"eu-de": "https://eu-de.atracker.cloud.ibm.com", // The server for IBM Cloud Activity Tracker Service in the eu-de region.
		"private.eu-de": "https://private.eu-de.atracker.cloud.ibm.com", // The server for IBM Cloud Activity Tracker Service in the eu-de region.
		"eu-gb": "https://eu-gb.atracker.cloud.ibm.com", // The server for IBM Cloud Activity Tracker Service in the eu-gb region.
		"private.eu-gb": "https://private.eu-gb.atracker.cloud.ibm.com", // The server for IBM Cloud Activity Tracker Service in the eu-gb region.
		"au-syd": "https://au-syd.atracker.cloud.ibm.com", // The server for IBM Cloud Activity Tracker Service in the au-syd region.
		"private.au-syd": "https://private.au-syd.atracker.cloud.ibm.com", // The server for IBM Cloud Activity Tracker Service in the au-syd region.
		"ca-tor": "https://us-east.atracker.cloud.ibm.com", // The server for IBM Cloud Activity Tracker Service for ca-tor points to the us-east region.
		"private.ca-tor": "https://private.us-east.atracker.cloud.ibm.com", // The server for IBM Cloud Activity Tracker Service for ca-tor points to the us-east region.
		"br-sao": "https://us-south.atracker.cloud.ibm.com", // The server for IBM Cloud Activity Tracker Service for br-sao points to the us-south region.
		"private.br-sao": "https://private.us-south.atracker.cloud.ibm.com", // The server for IBM Cloud Activity Tracker Service for br-sao points to the us-south region.
		"eu-fr2": "https://eu-de.atracker.cloud.ibm.com", // The server for IBM Cloud Activity Tracker Service for eu-fr2 points to the eu-de region.
		"private.eu-fr2": "https://private.eu-de.atracker.cloud.ibm.com", // The server for IBM Cloud Activity Tracker Service for eu-fr2 points to the eu-de region.
		"jp-tok": "https://eu-de.atracker.cloud.ibm.com", // The server for IBM Cloud Activity Tracker Service for jp-tok points to the eu-de region.
		"private.jp-tok": "https://private.eu-de.atracker.cloud.ibm.com", // The server for IBM Cloud Activity Tracker Service for jp-tok points to the eu-de region.
		"jp-osa": "https://eu-de.atracker.cloud.ibm.com", // The server for IBM Cloud Activity Tracker Service for jp-osa points to the eu-de region.
		"private.jp-osa": "https://private.eu-de.atracker.cloud.ibm.com", // The server for IBM Cloud Activity Tracker Service for jp-osa points to the eu-de region.
		"in-che": "https://eu-de.atracker.cloud.ibm.com", // The server for IBM Cloud Activity Tracker Service for in-che points to the eu-de region.
		"private.in-che": "https://private.eu-de.atracker.cloud.ibm.com", // The server for IBM Cloud Activity Tracker Service for in-che points to the eu-de region.
	}
```

**Comment by syyang-in-cloud** [comment]
or ... TFP needs to upgrade with the latest platform-service-go-sdk  of v0.28.5

**Comment by JohnPaulParkin** [comment]
I believe that this issue was resolved with the SDK changes mentioned above, but will only be in the TF releases starting with 1.47.0-beta0 and later due to the timing of the SDK updates and when the TF code picks up the latest dependencies.

**Comment by syyang-in-cloud** [comment]
I was waiting for the PR linked with the issue, but it seems someone just pushed the fix directly to `master`: https://github.com/IBM-Cloud/terraform-provider-ibm/commit/13e65b3c71aacfbd2dc5fe20fcb7e2624f7e0919

I hope @hkantare and admins can setup a kind of contribution rules with proper process to create PR and reviews, but it's up to them.

**Comment by SeungYeop-Yang** [comment]
Hi @JohnPaulParkin , I've tested with the latest TFP 1.47.0-beta0, and it's still failing as below:
```
ubuntu@21dad1628e04:/iaas-tfp/04-vpc-availability$ IBM_PROD_REGION="ca-tor" ./prod_test_terraform_init-upgrade_apply.sh 
+ [[ -z ca-tor ]]
+ for region in ${IBM_PROD_REGION}
+ echo ca-tor
ca-tor
+ terragrunt workspace select ca-tor -no-color
[INFO] Getting version from tgenv-version-name
[INFO] TGENV_VERSION is 0.38.12
+ terragrunt init -upgrade -no-color
[INFO] Getting version from tgenv-version-name
[INFO] TGENV_VERSION is 0.38.12

Initializing the backend...

Initializing provider plugins...
- Finding ibm-cloud/ibm versions matching "1.47.0-beta0"...
- Using previously-installed ibm-cloud/ibm v1.47.0-beta0

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
+ terragrunt apply -no-color -auto-approve -var-file=ca-tor.tfvars
[INFO] Getting version from tgenv-version-name
[INFO] TGENV_VERSION is 0.38.12
data.ibm_is_public_gateways.available: Reading...
data.ibm_is_subnets.available: Reading...
data.ibm_is_lbs.available: Reading...
data.ibm_is_snapshots.available: Reading...
data.ibm_is_volume_profiles.available: Reading...
data.ibm_iam_access_group.available: Reading...
data.ibm_is_operating_systems.available: Reading...
data.ibm_is_regions.available: Reading...
data.ibm_is_security_groups.available: Reading...
data.ibm_atracker_targets.available: Reading...
data.ibm_is_instances.available: Reading...
data.ibm_is_lbs.available: Read complete after 1s [id=2022-10-12 07:23:09.147532796 +0000 UTC]
data.ibm_is_ipsec_policies.available: Reading...
data.ibm_is_subnets.available: Read complete after 1s [id=2022-10-12 07:23:09.173275755 +0000 UTC]
data.ibm_is_vpcs.available: Reading...
data.ibm_is_public_gateways.available: Read complete after 1s [id=2022-10-12 07:23:09.178417963 +0000 UTC]
data.ibm_is_vpn_servers.available: Reading...
data.ibm_is_instances.available: Read complete after 1s [id=2022-10-12 07:23:09.228857838 +0000 UTC]
data.ibm_is_bare_metal_servers.available: Reading...
data.ibm_is_volume_profiles.available: Read complete after 1s [id=2022-10-12 07:23:09.265117213 +0000 UTC]
data.ibm_is_ipsec_policies.available: Read complete after 0s [id=2022-10-12 07:23:09.264960046 +0000 UTC]
data.ibm_is_lb_profiles.available: Reading...
data.ibm_is_dedicated_hosts.available: Reading...
data.ibm_is_vpn_servers.available: Read complete after 0s [id=2022-10-12 07:23:09.314429505 +0000 UTC]
data.ibm_dl_gateways.available: Reading...
data.ibm_is_vpcs.available: Read complete after 0s [id=2022-10-12 07:23:09.372768921 +0000 UTC]
data.ibm_is_network_acls.available: Reading...
data.ibm_is_lb_profiles.available: Read complete after 0s [id=2022-10-12 07:23:09.39791788 +0000 UTC]
data.ibm_atracker_routes.available: Reading...
data.ibm_is_dedicated_host_profiles.available: Reading...
data.ibm_is_operating_systems.available: Read complete after 1s [id=2022-10-12 07:23:09.431047005 +0000 UTC]
data.ibm_is_flow_logs.available: Reading...
data.ibm_is_network_acls.available: Read complete after 1s [id=2022-10-12 07:23:09.55637063 +0000 UTC]
data.ibm_tg_gateways.available: Reading...
data.ibm_is_security_groups.available: Read complete after 2s [id=2022-10-12 07:23:09.622245255 +0000 UTC]
data.ibm_is_bare_metal_server_profiles.available: Reading...
data.ibm_is_bare_metal_servers.available: Read complete after 1s [id=2022-10-12 07:23:09.665533296 +0000 UTC]
data.ibm_is_instance_templates.available: Reading...
data.ibm_dl_gateways.available: Read complete after 1s [id=2022-10-12 07:23:09.669735671 +0000 UTC]
data.ibm_is_placement_groups.available: Reading...
data.ibm_is_snapshots.available: Read complete after 2s [id=2022-10-12 07:23:09.734478463 +0000 UTC]
data.ibm_is_images.available: Reading...
data.ibm_is_flow_logs.available: Read complete after 1s [id=2022-10-12 07:23:09.818360588 +0000 UTC]
data.ibm_is_instance_groups.available: Reading...
data.ibm_is_instance_templates.available: Read complete after 0s [id=2022-10-12 07:23:09.929548047 +0000 UTC]
data.ibm_is_virtual_endpoint_gateways.available: Reading...
data.ibm_is_placement_groups.available: Read complete after 0s [id=2022-10-12 07:23:09.945297047 +0000 UTC]
data.ibm_is_endpoint_gateway_targets.available: Reading...
data.ibm_is_dedicated_hosts.available: Read complete after 1s
data.ibm_is_ssh_keys.available: Reading...
data.ibm_is_virtual_endpoint_gateways.available: Read complete after 0s [id=2022-10-12 07:23:10.191943922 +0000 UTC]
data.ibm_is_ike_policies.available: Reading...
data.ibm_is_ssh_keys.available: Read complete after 0s [id=2022-10-12 07:23:10.208796547 +0000 UTC]
data.ibm_is_floating_ips.available: Reading...
data.ibm_is_instance_groups.available: Read complete after 0s [id=2022-10-12 07:23:10.291174672 +0000 UTC]
data.ibm_is_volumes.available: Reading...
data.ibm_is_bare_metal_server_profiles.available: Read complete after 0s [id=2022-10-12 07:23:10.315503213 +0000 UTC]
data.ibm_is_instance_profiles.available: Reading...
data.ibm_is_ike_policies.available: Read complete after 0s [id=2022-10-12 07:23:10.332823672 +0000 UTC]
data.ibm_is_vpn_gateways.available: Reading...
data.ibm_is_floating_ips.available: Read complete after 0s [id=2022-10-12 07:23:10.342477755 +0000 UTC]
data.ibm_is_dedicated_host_groups.available: Reading...
data.ibm_is_dedicated_host_groups.available: Read complete after 0s
data.ibm_iam_access_group.available: Read complete after 2s [id=c560c8e42d2f49a48210811bd6f5ee73]
data.ibm_is_vpn_gateways.available: Read complete after 0s [id=2022-10-12 07:23:10.484114839 +0000 UTC]
data.ibm_is_volumes.available: Read complete after 1s [id=2022-10-12 07:23:10.829349505 +0000 UTC]
data.ibm_is_instance_profiles.available: Read complete after 1s [id=2022-10-12 07:23:11.016442464 +0000 UTC]
data.ibm_is_endpoint_gateway_targets.available: Read complete after 2s [id=2022-10-12 07:23:11.653943256 +0000 UTC]
data.ibm_is_dedicated_host_profiles.available: Read complete after 4s [id=2022-10-12 07:23:12.579343215 +0000 UTC]
data.ibm_is_images.available: Read complete after 3s [id=2022-10-12 07:23:12.800247006 +0000 UTC]
data.ibm_is_regions.available: Read complete after 8s [id=2022-10-12 07:23:15.664742341 +0000 UTC]
data.ibm_atracker_targets.available: Still reading... [10s elapsed]
data.ibm_atracker_routes.available: Still reading... [10s elapsed]
data.ibm_tg_gateways.available: Still reading... [10s elapsed]
data.ibm_tg_gateways.available: Read complete after 17s [id=2022-10-12 07:23:26.729424096 +0000 UTC]

Error: service URL for region 'ca-tor' not found

  with data.ibm_atracker_routes.available,
  on main.tf line 45, in data "ibm_atracker_routes" "available":
  45: data "ibm_atracker_routes" "available" {}


Error: service URL for region 'ca-tor' not found

  with data.ibm_atracker_targets.available,
  on main.tf line 46, in data "ibm_atracker_targets" "available":
  46: data "ibm_atracker_targets" "available" {}

ERRO[0020] Terraform invocation failed in /iaas-tfp/04-vpc-availability 
ERRO[0020] 1 error occurred:
        * exit status 1
          
ubuntu@21dad1628e04:/iaas-tfp/04-vpc-availability$
```

I checked out the tag v1.47.0-beta0, and it seems go.mod was not updated yet: https://github.com/IBM-Cloud/terraform-provider-ibm/blob/420da5ab6e7a58419ac5ef178ddd56de4533c8a4/go.mod#L25

**Comment by hkantare** [comment]
@SeungYeop-Yang This we need to check with Atracker team who handles the support veenar@us.ibm.com is newly onboarded who owns the support

**Comment by JohnPaulParkin** [comment]
@SeungYeop-Yang - the reason for the URL mapping is that ATracker is not supported in all regions at the moment.  The supported regions are documented in the external cloud docs.  As a result, there is no ca-tor.atracker.cloud.ibm.com endpoint to operate against when performing the operations from one of the unsupported environments.

This poses a problem when someone is attempting to leverage ATracker to deliver the global events that are normally delivered to eu-de to a different region ( such as ca-tor or jp-tok ).  Presumably the region in which the terraform is being executed is one of those locations just because that's the default the user normally configures and the TF provider attempts to match the atracker.cloud.ibm.com with that region ( which results in this problem ).
