### ISSUE TITLE
ibm_pi_network: bad request: ip address range is not valid

### ISSUE THREAD

**Issue by aklyachkin** [IBM-Cloud/terraform-provider-ibm#843]
### Terraform Version
Terraform v0.11.14
IBM Cloud provider 0.18.0

### Affected Resource(s)
ibm_pi_network

### Terraform Configuration Files
```hcl
resource "ibm_pi_network" "aix_net" {
  pi_network_name      = "aix_net"
  pi_network_type      = "vlan"
  pi_dns               = ["8.8.8.8"]
  pi_cidr              = "10.0.0.0/24"
  pi_cloud_instance_id = "${var.pi_cloud_id}"
}
```

### Panic Output
no panic

### Expected Behavior
network is created

### Actual Behavior
```
Error: Error applying plan:

1 error occurred:
	* ibm_pi_network.aix_net: 1 error occurred:
	* ibm_pi_network.aix_net: {"description":"bad request: ip address range [10.0.0.2-10.0.0.254] is not valid for cidr 10.0.0.0/24 (note: ip addresses 10.0.0.1 through 10.0.0.3 are reserved and cannot be used); ip address range(s) must be less than or equal to the range [10.0.0.4-10.0.0.254]","error":"bad request"}
```

### Steps to Reproduce
1. `terraform apply`

**Comment by surajsub** [comment]
Code has been updated and fixed in the latest release of the provider

**Comment by aklyachkin** [comment]
I built the latest commit and unfortunaltey the error is still there:

```
	* ibm_pi_network.aix_net: 1 error occurred:
	* ibm_pi_network.aix_net: {"description":"bad request: ip address range [10.0.0.18-10.0.0.30] is not valid for cidr 10.0.0.16/28 (note: ip addresses 10.0.0.17 through 10.0.0.19 are reserved and cannot be used); ip address range(s) must be less than or equal to the range [10.0.0.20-10.0.0.30]","error":"bad request"}
```

**Comment by surajsub** [comment]
Can you provide a clean terraform.log please ? I just validated this and it works just fine.

**Comment by aklyachkin** [comment]
gist with the log https://gist.github.com/aklyachkin/69d7ed190c6cd8541f07e133f97f99a2

Output:
```
ibm_pi_network.aix_net: Creating...
  pi_cidr:              "" => "10.0.0.16/28"
  pi_cloud_instance_id: "" => "5e605dfb-024f-4d71-9424-43303a8860d8"
  pi_dns.#:             "0" => "1"
  pi_dns.2609393598:    "" => "8.8.8.8"
  pi_network_name:      "" => "aix_net"
  pi_network_type:      "" => "vlan"
  pi_networkid:         "" => "<computed>"
  pi_vlan_id:           "" => "<computed>"

Error: Error applying plan:

1 error occurred:
	* ibm_pi_network.aix_net: 1 error occurred:
	* ibm_pi_network.aix_net: {"description":"bad request: ip address range [10.0.0.18-10.0.0.30] is not valid for cidr 10.0.0.16/28 (note: ip addresses 10.0.0.17 through 10.0.0.19 are reserved and cannot be used); ip address range(s) must be less than or equal to the range [10.0.0.20-10.0.0.30]","error":"bad request"}





Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
```

Configuration:
```
provider "ibm" {
  ibmcloud_api_key    = "${var.ibmcloud_api_key}"
  iaas_classic_username = "${var.iaas_classic_username}"
  iaas_classic_api_key  = "${var.iaas_classic_api_key}"
  region                = "${var.ibmcloud_region}"
}

resource "ibm_pi_network" "aix_net" {
  pi_network_name      = "aix_net"
  pi_network_type      = "vlan"
  pi_dns               = ["8.8.8.8"]
  pi_cidr              = "10.0.0.16/28"
  pi_cloud_instance_id = "${var.pi_cloud_id}"
}
```

**Comment by aklyachkin** [comment]
it looks like in the new version the problem is fixed. As for me it works now with version 1.2.2.
